BusinessManagement/views/admin.py
import csv
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        
        #ucid: jp2267    date: 11-17-2022
        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        mystr = file.filename
        if mystr.endswith('.csv'):
            flash('data is uploded successfully',"success")
        else:
            flash('Please upload a .csv file', "warning")
            return redirect(request.url)
        
        if file and secure_filename(file.filename):
            companies = []
            employees = []
            company_query = """
            INSERT INTO IS601_MP2_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(company_name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(web)s)
                        ON DUPLICATE KEY UPDATE address = %(address)s, city = %(city)s, country=%(country)s, state=%(state)s, zip=%(zip)s, website=%(web)s 
            """
            employee_query = """
            INSERT INTO IS601_MP2_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, last_name = %(last_name)s, email = %(email)s, company_id = (SELECT id FROM IS601_MP2_Companies WHERE name = %(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            
            # TODO importcsv-2 read the csv file stream as a dict
            for row in csv.DictReader(stream, delimiter=','):
                print(row) #example
                # TODO importcsv-3 extract company data and append to company list as a dict only with company data
                if row["company_name"] and row["address"] and row["city"] and row["state"] and row["zip"] and row["web"]:
                    companies.append(row)

                # TODO importcsv-4 extract employee data and append to employee list as a dict only with employee data
                if row["first_name"] and row["last_name"] and row["email"] and row["company_name"]:
                    employees.append(row)
                
                #pass
               
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                    flash(f"Inserting or updating {len(companies)} companies","sucess")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                flash("no companies were loaded into database", "danger")
                #pass
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    # TODO importcsv-7 display flash message about number of employees loaded
                    flash(f"Inserting or updating {len(employees)} employees","sucess")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-8 display flash message (info) that no companies were loaded
                flash("no employees were loaded into datbase", "danger")
                #pass
    return render_template("upload.html")

BusinessManagement/views/company.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from sql.db import DB
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():

    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count for the company
    # don't do SELECT *
    query = "SELECT id, name, address, city, country, state, zip, website FROM IS601_MP2_Companies WHERE 1=1"
        
    args = [] # <--- append values to replace %s placeholders
    allowed_columns = ["name", "city", "country", "state"]
    
    # TODO search-2 get name, country, state, column, order, limit request args
    name = request.args.get("name")
    country = request.args.get("country")
    state = request.args.get("state")
    col = request.args.get("column")
    order = request.args.get("order")
    limit = request.args.get("limit", 10) 

    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds

    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND IS601_MP2_Companies.name like %s"
        args.append(f"%{name}%")

    # TODO search-4 append an equality filter for country if provided
    if country:
        query += " AND IS601_MP2_Companies.country like %s"
        args.append(f"%{country}%")

    # TODO search-5 append an equality filter for state if provided
    if state:
        query += " AND IS601_MP2_Companies.state like %s"
        args.append(f"%{state}%")
    
    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    if col and order:
        if col in allowed_columns \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {col} {order}"
    
    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    if limit and int(limit) > 0 and int(limit) <= 100 :
        query += " LIMIT %s"
        args.append(int(limit))
    else:
        flash('limit should be a numeric value or try entering 1 or 100 ', "warning")
        return redirect(request.url)  

    print("query",query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        if result.status:
            rows = result.rows
    except Exception as e:
        # TODO search-9 make message user friendly
        flash('There was an error getting company records', "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    allowed_list = [(v,v) for v in allowed_columns]
    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_list)

@company.route("/add", methods=["GET","POST"])
def add():
    if request.method == "POST":
    
        has_error = False # use this to control whether or not an insert occurs

        #jp2267 3 Dec
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        n = request.form.get("name", None)
        ad = request.form.get("address", None)
        c = request.form.get("city", None)
        s = request.form.get("state", None)
        country = request.form.get("country", None)
        z = request.form.get("zip", None)
        w = request.form.get("website", None)

        # TODO add-2 name is required (flash proper error message)
        if n == "":
            flash('Company name is required', "danger")
            has_error = True

        # TODO add-3 address is required (flash proper error message)
        if ad == "":
            flash('Address is required', "danger")
            has_error = True

        # TODO add-4 city is required (flash proper error message)
        if c == "":
            flash('City is required', "danger")
            has_error = True

        # TODO add-5 state is required (flash proper error message)
        if s == "":
            flash('State is required', "danger")
            has_error = True

        # TODO add-6 country is required (flash proper error message)
        if country == "":
            flash('Country is required', "danger")
            has_error = True

        # TODO add-7 website is not required
        if w == "":
            pass

        #jp2267 3 Dec
        if not has_error:
            try:
                result = DB.insertOne("""
                INSERT
                INTO IS601_MP2_Companies (name,address,city,country,state,zip,website)
                VALUES(%s, %s, %s, %s, %s, %s, %s)""", n,ad,c,country,s,z,w) # <-- TODO add-8 add query and add arguments
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                flash('There was something wrong while adding the company data', "danger")
        
    return render_template("add_company.html")

@company.route("/edit", methods=["GET", "POST"])
def edit():
    # TODO edit-1 request args id is required (flash proper error message)
    
    id = request.args.get("id")
    resp = None
    row = None
    
    print("request", request.args)


    if id is None: # TODO update this for TODO edit-1
        return redirect("company.search")
    else:
        if request.method == "POST":
            # TODO edit-2 retrieve form data for name, address, city, state, country, zip, website
            # TODO edit-3 name is required (flash proper error message)
            # TODO edit-4 address is required (flash proper error message)
            # TODO edit-5 city is required (flash proper error message)
            # TODO edit-6 state is required (flash proper error message)
            # TODO edit-7 country is required (flash proper error message)
            # TODO edit-8 website is not required
            # 
            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            #data = [name, address, city, state, country, zipcode, website]
            #data.append(id)
            n = request.form.get("name")
            ad = request.form.get("address")
            ci = request.form.get("city")
            s = request.form.get("state")

            co = request.form.get("country")
            z = request.form.get("zip")
            w = request.form.get("website")

            print(request.args.get("country" + "no country found")) 
            try:
                # TODO edit-9 fill in proper update query
                result = DB.update("""
                UPDATE IS601_MP2_Companies SET 
                name = %s,
                address = %s,
                city = %s,
                state = %s,
                country = %s,
                zip = %s,
                website = %s
                WHERE id = %s
                """, n,ad,ci,s,co,z,w,id)

                if result.status:
                    resp = "Updated"
                    flash("Updated record", "success")
            except Exception as e:
                # TODO edit-10 make this user-friendly
                flash(str(e), "danger")
        try:
            # TODO edit-11 fetch the updated data
            result = DB.selectOne("SELECT id, name, address, city, country, state, zip, website FROM IS601_MP2_Companies WHERE id = %s", id)
            if result.status:
                row = result.row
                print(row)
        except Exception as e:
            # TODO edit-12 make this user-friendly
            flash(str(e), "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", row=row, resp=resp)

@company.route("/delete", methods=["GET"])
def delete():
    if request.args.get('id', '' ) == '':
        flash('id is required', "danger")

    id = request.args.get('id', '' )
    # TODO delete-1 delete company by id (unallocate any employees)
    try:
        pass
        employees_result = DB.update("""
                UPDATE IS601_MP2_Employees SET company_id=null WHERE company_id=%s
                """, id)

        result = DB.delete("DELETE FROM IS601_MP2_Companies WHERE id=%s", id)
        if result.status:
            # TODO delete-4 ensure a flash message shows for successful delete
            flash("Company record successfully deleted", "success")
    except Exception as e:
        # TODO edit-9 make this user-friendly
        print(str(e))
        flash("There was an error deleting company record", "danger")

    # TODO delete-2 redirect to company search
    # TODO delete-3 pass all argument except id to this route
    return redirect(url_for('company.search', name="", country="", state="",order="asc", column="", limit=10))

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    status = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        list(pycountry.subdivisions.get(country_code=request.args.get('country_code', 'US')))))
    return json.dumps(status)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            #}
            <label class="form-label" for="fn">name</label>
            <input type="text" class="form-control" id="n" name="name" />
            
            <label class="form-label" for="ln">address</label>
            <input type="text" class="form-control" id="ad" name="address" />            

            <label class="form-label" for="fn">city</label>
            <input type="text" class="form-control" id="n" name="city" />
            
            <label class="form-label" for="fn">zip</label>
            <input type="text" class="form-control" id="n" name="zip" />
            
            <label class="form-label" for="ln">website</label>
            <input type="text" class="form-control" id="ad" name="website" /> 

            {# use this for country/state selection #}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            first_name
            last_name
            email
            #}
            {#ucid: jp2267    date: 11-17-2022#}
            <label class="form-label" for="fn">First Name</label>
            <input type="text" class="form-control" id="fn" name="first_name" />
            
            <label class="form-label" for="ln">Last Name</label>
            <input type="text" class="form-control" id="ln" name="last_name" />

            <label class="form-label" for="e">Email</label>
            <input type="email" class="form-control" id="e" name="email" />

            <!--<label class="form-label" for="c">company</label>-->
            {# use the below for company selection #}
            {% include "company_dropdown.html" %}
            </br>
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% set comps = get_companies() %}
{# can set val prior to inclusion to prefill this field #}
{# TODO DO NOT EDIT #}
<div class="col-12">
    <label class="form-label" for="company">Company</label>
    <select class="form-select" name="company" value="{{val or ''}}">
        <option value="">No Company</option>
        {% for c in comps %}
        {# example of using external data setting and casting #}
        <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
        {% endfor %}
    </select>
</div>

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col-12">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{request.args.get('country', '')}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col-12">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{request.args.get('state', '')}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{request.args.get('country', '')}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{request.args.get('state', '')}}">
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{request.args.get('state', '')}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{request.args.get('country', 'US')}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>

BusinessManagement/templates/edit_company.html
{% extends "layout.html" %}
{% block title %}Edit Company{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Company</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            name
            address
            city
            website
            and prefill the fields with loaded company data
            #}
            
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" readonly value="{{row.id}}" />
            </div>            
            
            <div class="form-group mb-3">
                <label class="form-label" for="n">Company Name</label>
                <input class="form-control" id="n" name="name" value="{{row.name}}" />
            </div>

            <div class="form-group mb-3">
                <label class="form-label" for="ad">Address</label>
                <input class="form-control" id="ad" name="address" value="{{row.address}}" />
            </div>

            <div class="form-group mb-3">
                <label class="form-label" for="ci">City</label>
                <input class="form-control" id="ci" name="city" value="{{row.city}}" />
            </div>

            <div class="form-group mb-3">
                <label class="form-label" for="z">Zip</label>
                <input class="form-control" id="z" name="zip" value="{{row.zip}}" />
            </div>

            <div class="form-group mb-3">
                <label class="form-label" for="w">Website</label>
                <input class="form-control" id="w" name="website" value="{{row.website}}" />
            </div>

            <div class="form-group mb-3">
                <label class="form-label" for="co">country</label>
                <input class="form-control" id="co" name="country" value="{{row.country}}" />
            </div>

            {# use this for country/state selection #}
            {% set country = row.country %}
            {% set state = row.state %}
            {% include "country_state_selector.html" %}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
        {% if resp %}
        <div id="output">
            {{resp}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

BusinessManagement/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

BusinessManagement/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            display: block;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - MP2</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                {# TODO replace my ucid mt85 with your ucid #}
                <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-jp2267</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {# TODO fill in the relevant hrefs using url_for() #}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- company dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Company
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                            </ul>
                        </li>
                        <!-- employee dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Employee
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                                <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                            </ul>
                        </li>
                        <!-- admin dropdown nav -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% include 'flash.html' %}
    </div>
    <div id="content" class="overflow-scroll" style="height: 84vh">
        {% block content %} {% endblock %}
    </div>
    <div id=" footer" class="footer mt-auto py-3 bg-light text-center fixed-bottom">
        <div class="container">
            {% block footer %}
            <span>Business Management &copy; Copyright 2022.</span>
            {% endblock %}
        </div>
    </div>
</body>

</html>

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (company name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit
    ensure all fields prefill with request arg data if provided
    #}
    <form method="GET" class="row row-cols-lg-auto g-3 align-items-center">    

        <div class="col-12">
            <label class="form-label" for="name">Company Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Company Name"
                value="{{request.args.get('name') or ''}}">
        </div>

        {% with layout = "horizontal" %}
        {% include "country_state_selector.html" %}
        {% endwith %}
        {% with cols = allowed_columns %}
        {% include "sort_filter.html" %}
        {% endwith %}

        <div class="col-12">
            <label class="form-label" for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>

        <div class="col-12">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </div>
        <div class="col-12">
            <a href="?" class="btn btn-secondary">Reset</a>
        </div>
    </form>
    <div class="table-responsive">
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# IMPORTANT use table column names as the headings, replace _ with space #}
                {% for r in rows[0] %}
                    <th>{{r | replace("_"," ")}}</th>
                {% endfor %}
                <th>Actions</th>
            </tr>
        </thead>
        {% for r in rows %}
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# if the td is for website, display it as a link where the text is "website" and the url is the
            website url #}
            {# in the last column add the following
            a view button that passes the company id to employee search (this will be a company employee
            directory) also pass company_name as an argument
            an edit button that passes the company id to company edit
            a delete button that passes the company id and the request args to the company delete route
            #}
            {% for v in r.values() %}
            <td>{{v}}</td>
            {% endfor %}
            <td><a href="{{url_for('company.edit', id=r.get('id'), country=r.get('country'), state=r.get('state'))}}" class="btn btn-secondary btn-sm">Edit</a>
                {# **request.args spreads the key value pairs to be part of the url#}
                {# the idea is to pass it to the next route #}
                <a href="{{url_for('company.delete', id=r.get('id'), **request.args)}}"
                    class="btn btn-danger btn-sm">x</a>
            </td>
        </tbody>
        {% endfor %}
        {% else %}
        <tbody>
            <tr>
                <td colspan="100%">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    </div>
</div>
{% endblock %}