flask_sample/main.py
# from https://towardsdatascience.com/deploy-to-google-cloud-run-using-github-actions-590ecf957af0
import os
import sys
from flask import Flask

# added so modules can be found between the two different lookup states:
# from tests and from regular running of the app
CURR_DIR = os.path.dirname(os.path.abspath(__file__))
print(CURR_DIR)
sys.path.append(CURR_DIR)


# app = Flask(__name__)
def create_app(config_filename=''):
    app = Flask(__name__)
    # app.config.from_pyfile(config_filename)
    with app.app_context():
        from views.hello import hello
        app.register_blueprint(hello)
        from views.sample import sample
        app.register_blueprint(sample)
        return app
        
    # DON'T DELETE, this cleans up the DB connection after each request
    # this avoids sleeping queries
    @app.teardown_request 
    def after_request_cleanup(ctx):
        from sql.db import DB
        DB.close()
    return app

app = create_app()
if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

flask_sample/views/hello.py
from flask import Blueprint, request
hello = Blueprint('hello', __name__, url_prefix='/')


@hello.route('/')
def index():
    name = request.args.get('name', 'World')
    return f'Hello {name}!'

flask_sample/views/sample.py
from flask import Blueprint, request, render_template, redirect, url_for

from sql.db import DB
sample = Blueprint('sample', __name__, url_prefix='/sample')


@sample.route('/add', methods=['GET','POST'])
def add():
    k = request.form.get("key", None)
    v = request.form.get("value", None)
    resp = None
    if k and v:
        try:
            result = DB.insertOne("INSERT INTO IS601_Sample (name, val) VALUES(%s, %s)", k, v)
            if result.status:
                resp = "Saved record"
        except Exception as e:
            resp = e
        

    return render_template("add_sample.html", resp=resp)

@sample.route('/list', methods=['GET'])
def list():
    key = request.args.get("name")
    col = request.args.get("col")
    order = request.args.get("order")
    limit = request.args.get("limit", 10)
    args = []
    print(f"col {col} order {order}")
    # dynamically build our query and data mappings
    # use the WHERE true trick so we can easily append conditions without caring if a condition
    # already was applied (no need to check if WHERE exists)
    query = "SELECT id, name, val, created, modified from IS601_Sample WHERE 1=1"
    if key:
        query += " AND name like %s"
        args.append(f"%{key}%")
    if col and order:
        # incorrect
        # these get passed as safe strings rather than sql keywords
        # query += f" ORDER BY %s %s"
        # args.append(col)
        # args.append(order)
        # correct - validate fully that col and order are expected values
        # this will be directly injected and if not validated could
        # lead to sql injection
        if col in ["name","val","created","modified"] \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {col} {order}"

    if limit and int(limit) > 0 and int(limit) <= 100:
        # technically this should follow the same rules as col/order
        # but it seems to work with the placeholder mapping with
        # this connector
        query += " LIMIT %s"
        args.append(int(limit))
    rows = []
    error = None
    try:
        # convert our list to args via *
        print(query)
        resp = DB.selectAll(query, *args)
        if resp.status:
            rows = resp.rows
    except Exception as e:
        error = e
    
    return render_template("list_sample.html", resp=rows, error=error)

@sample.route("/edit", methods=["GET", "POST"])
def edit():
    id = request.args.get("id")
    resp = None
    row = None
    if id is None:
        return redirect("sample.list")
    else:
        if request.method == "POST" and request.form.get("value"):
            val = request.form.get("value")
            try:
                result = DB.update("UPDATE IS601_Sample SET val = %s WHERE id = %s", val, id)
                if result.status:
                    resp = "Updated"
            except Exception as e:
                resp = e
        try:
            result = DB.selectOne("SELECT name, val FROM IS601_Sample WHERE id = %s", id)
            if result.status:
                row = result.row
        except Exception as e:
            resp = e
    return render_template("edit_sample.html", row=row, resp=resp)

@sample.route("/delete", methods=["GET"])
def delete():
    id = request.args.get("id")
    # make a mutable dict
    args = {**request.args}
    if id:
        result = DB.delete("DELETE FROM IS601_Sample WHERE id = %s", id)
        # TODO pass along feedback

        # remove the id args since we don't need it in the list route
        # but we want to persist the other query args
        del args["id"]
    return redirect(url_for("sample.list", **args))

flask_sample/templates/add_sample.html
{% extends "layout.html" %}
{% block title %}Add Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" />
            </div>
            <input type="submit" class="btn btn-primary" value="Save Sample" />
        </form>
        {% if resp %}
        <div id="output">
            {{resp}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

flask_sample/templates/edit_sample.html
{% extends "layout.html" %}
{% block title %}Edit Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" readonly value="{{row.name}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" value="{{row.val}}" />
            </div>
            <input type="submit" class="btn btn-primary" value="Update Sample" />
        </form>
        {% if resp %}
        <div id="output">
            {{resp}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

flask_sample/templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - Sample</title>
    {% endblock %}
</head>

<body>
    <div id="header" class="header bg-light text-center">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Sample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('sample.add')}}">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('sample.list')}}">List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer" class="footer bg-light text-center">
        {% block footer %}
        &copy; Copyright 2022.
        {% endblock %}
    </div>
</body>

</html>

flask_sample/templates/list_sample.html
{% extends "layout.html" %}
{% block title %}List Samples{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">List Samples</div>
    <form class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
            <label class="form-label" for="name">Name/Key</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="name/key"
                value="{{request.args.get('name') or ''}}">
        </div>
        <div class="col-12">
            {% set options = ["name", "val", "modified", "created"] %}
            <label class="form-label" for="col">Column</label>
            {# notice value doesn't work for server-side built selects
            that's because the value is set before the options exist so it doesn't pick the proper
            option, instead we need to manually select the correct option or use a JS hack #}
            <select class="form-select" id="col" name="col" value="{{request.args.get('col')}}">
                <option value="">Choose...</option>
                {% for op in options %}
                {# using an inline if to output the selected attribute if it matches the op #}
                <option {{'selected' if request.args.get('col')==op }} value="{{op}}">{{op|capitalize}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="order">Order</label>
            <select class="form-select" id="order" name="order" value="{{request.args.get('order')}}">
                <option value="">Choose...</option>
                <option {{'selected' if request.args.get('order')=="asc" }} value="asc">+</option>
                <option {{'selected' if request.args.get('order')=="desc" }} value="desc">-</option>
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>
        <div class="col-12">
            <!-- hack to align button with inputs in inline form with labels-->
            <div>&nbsp;</div>
            <button type="submit" class="btn btn-primary mt-2">Filter</button>
            <!--trick to reset a prefilled form to empty-->
            <a href="?" class="btn btn-secondary mt-2">Reset</a>
        </div>
    </form>
    <table class="table">
        {% if resp and resp|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {% for r in resp[0] %}
                <th>{{r}}</th>
                {% endfor %}
            </tr>
        </thead>
        {% for r in resp %}
        <tr>
            {% for v in r.values() %}
            <td>{{v}}</td>
            {% endfor %}
            <td><a href="{{url_for('sample.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                {# **request.args spreads the key value pairs to be part of the url#}
                {# the idea is to pass it to the next route #}
                <a href="{{url_for('sample.delete', id=r.get('id'), **request.args)}}"
                    class="btn btn-danger btn-sm">x</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <p>No results to show</p>
        {% endif %}
</div>
{% if error %}
{{error}}
{% endif %}
</div>
{% endblock %}